apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jmjohn732-poi-map-app-dev
  annotations:
    argocd/app-name: jmjohn732-poi-map-app-dev
    backstage.io/kubernetes-id: jmjohn732-poi-map-app
    backstage.io/kubernetes-namespace: jmjohn732
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/jmjohn732-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/jmjohn732/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/jmjohn732/deployments/jmjohn732-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/jmjohn732-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://jmjohn732-poi-map-app-jmjohn732.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/jmjohn732"
  system: workshop-system-jmjohn732
  consumesApis:
    - gateway-api-jmjohn732
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-jmjohn732
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/jmjohn732"
